Section "InputClass"
    Identifier "Beken Wireless Mouse"
    MatchDriver "libinput"
    MatchProduct "Beken 2.4G Wireless Device"
    MatchIsPointer "on"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
EndSection
